name = "django"
title = "Django MongoDB Backend"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = [
    "/interact-data"
]

[constants]
django-odm = "Django MongoDB Backend"
django-api = "https://django-mongodb.readthedocs.io/en/latest/"
mdb-server = "MongoDB Server"
