name = "django"
title = "Django MongoDB Backend"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = [
    "/get-started"
]

[constants]
django-odm = "Django MongoDB Backend"
api = "https://django-mongodb.readthedocs.io/en/latest/"
mdb-server = "MongoDB Server"
django-version = "5.0"
django-docs = "https://docs.djangoproject.com/en/{+django-version+}"
django-api = "https://django-mongodb-backend.readthedocs.io/en/latest/"
pymongo-version = "4.10"